src/lib/components/button/button.svelte, src/lib/components/input/asset.svelte, src/lib/components/input/textinput.svelte, src/routes/(dev)/debug/components/sections/buttons.svelte, src/routes/(dev)/debug/components/sections/inputs.svelte, src/routes/(dev)/debug/input/asset/+page.svelte
- Add disabled styles to primary and secondary buttons
- Add examples to components page
- Class strings on newlines for better diffs going forward
=> Add disabled styles to buttons

Makefile
Expose the dev server to the local network for easy testing on other devices (e.g. mobile)
=> Expose dev server to local network

src/app.html, src/lib/components/layout/stack.svelte, src/lib/components/table/body.svelte, src/lib/components/table/cell.svelte, src/lib/components/table/head.svelte, src/lib/components/table/header.svelte, src/lib/components/table/index.ts, src/lib/components/table/root.svelte, src/lib/components/table/row.svelte, src/routes/[network]/(dev)/debug/components/+page.svelte, src/routes/[network]/(dev)/debug/components/sections/tables.svelte
Basic implementation of the table design found in Figma
As more use cases arise, we'll add more complexity including:
- sorting
- filtering
- hidden columns at breakpoints
- etc.
=> Add table component

src/app.css, src/app.html, src/lib/components/input/search.svelte, src/routes/[network]/+layout.svelte
Style changes to fix the root layout on mobile.
Also adds a max width to the main content area to prevent hhhhuuuuuuuuuuuugggeeeee buttons
=> Fix mobile layout

.github/workflows/check.yml
Add type checking with `tsc --noemit` to the Code Checks github action
=> ci: add tsc to github actions

src/lib/state/client/account.svelte.ts, src/lib/types.ts
The server returns an array of balances (LightAPIBalanceRow[])
=> fix account balances parse

docker-compose.yaml, src/lib/components/input/search.svelte, src/lib/state/search.svelte.ts, src/lib/utils/index.ts
Saves search history to localstorage
Add function to clear individual and all items from history
=> Search dialog improvements

src/routes/[network]/+layout.svelte
Allow the user to hide the v1 banner
Saves the preference to localStorage
Defaults to hide the banner, shows it if the flag isn't set (this avoids flash of banner when the user requested to hide it)
=> feat: hide v1 banner

src/routes/[network]/(homepage)/+page.svelte
- Fix layout of early access homepage content
- Content edits
=> Content edits

src/routes/[network]/(account)/ram/+page.svelte
https://greymass.slack.com/archives/C02EN8NRTL4/p1731499784762609?thread_ts=1731462220.998119&cid=C02EN8NRTL4
=> Merging all RAM market values into one card

src/lib/components/elements/cpunetresource.svelte
@ttwishing these were all the changes I made in my branch so I cherrypicked them into this PR for you
=> style: simplify css

src/app.css, src/lib/components/pageheader.svelte, src/routes/[network]/(homepage)/(wallets)/metamask/+page.svelte
Updated some styling and made some content edits
=> Metamask landing page enhancements

src/app.css, src/routes/[network]/+layout.svelte
- fill screen better on tablet sizes
- improve touch responsiveness on mobile devices by not waiting for double tap event
=> More style updates

src/lib/components/elements/block.svelte, src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/+layout.svelte, src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/+page.svelte
- Adds a basic empty state for no-action transactions
- Hides the data tab under debug flag
- Comment out some currently unused code to make the red squiggles go away
- Adds a block formatter component to be used here eventually
=> Handle no-action transactions more gracefully

src/routes/[network]/(explorer)/key/[publicKey]/+page.svelte
quick fix for the incorrect multicolumn layout on key page
=> fix: layout of key page

src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/traces/+page.svelte
=> Group notification traces to deduplicate on the transaction page

src/lib/components/navigation/mobilenavigation.svelte, src/lib/components/navigation/sidemenu.svelte, src/routes/[network]/+layout.svelte
Refactors the root layout to allow for a sticky side menu
This refactor also sets the groudwork for a collapsible side menu on desktop #269
=> refactor: sticky side menu

src/lib/components/accountswitch.svelte, src/lib/components/input/text.svelte, src/lib/components/networkswitch.svelte
Add connect wallet buttons to account switcher to improve first login experience
=> Account switcher update

src/lib/components/accountswitch.svelte
=> fix: account switch filter bug

src/lib/components/button/icon.svelte, src/lib/components/elements/asset.svelte, src/routes/[network]/(account)/swap/[basecontract]/[basesymbol]/[quotecontract]/[quotesymbol]/+page.svelte
Fixes mobile and follows figma design while fixing some style bugs
=> Swap page design

src/routes/[network]/(account)/upload/[[name]]/+page.svelte, src/routes/[network]/(account)/upload/[[name]]/+page.ts, src/routes/[network]/(explorer)/account/[name]/+page.svelte, src/routes/[network]/(explorer)/contract/[contract]/+page.svelte
Also removed button from My Account page, and instead put it on the contract page.
The root /upload url will allow uploading to any account
=> Moved upload contract to standalone page

src/lib/components/chart/chart-container.svelte, src/lib/components/chart/line-chart.svelte, src/lib/components/chart/loading.svelte, src/routes/[network]/(explorer)/account/[name]/permissions/permission.svelte
Fixes chart colors 
Enables semantic color on the charts (e.g. green when up, red when down)
Fixes background color issue with permission cards in the permission tree
=> Chart style updates

src/lib/components/button/button.svelte, src/lib/components/form/fileUpload.svelte
Solid background disabled buttons
Dashed outline upload zone
=> revert: disabled button styles

src/lib/components/summary/components/balancechange.svelte, src/lib/components/summary/components/container.svelte, src/lib/components/summary/components/row.svelte, src/lib/components/summary/components/transfer.svelte, src/lib/components/summary/eosio/buyrambytes.svelte, src/lib/components/summary/eosio/powerup.svelte
Fixes the styling on the summary elements so they are readable vertically on smaller viewports
=> style: update summary styling

src/lib/components/descriptionlist/dl.svelte, src/lib/components/elements/asset.svelte, src/lib/components/input/text.svelte, src/lib/components/layout/page/multicard.svelte, src/lib/components/transact/summary.svelte, src/routes/[network]/(account)/(send)/send/[[contract]]/[[symbol]]/+page.svelte, src/routes/[network]/(account)/ram/+page.svelte, src/routes/[network]/(account)/staking/+page.svelte, src/routes/[network]/(explorer)/block/[number]/+page.svelte, src/routes/[network]/(explorer)/contract/[contract]/actions/[action]/[[data]]/+page.svelte
Fixes some layout and styling issues in safari/webkit
=> Safari fixes

configs/.env.spring2.testnet
Dynamic image path wasn't working removed it reverting back to wharfkit cnd png for vaulta.
=> removed broken image

src/lib/components/navigation/pillgroup.svelte, src/lib/components/select/language.svelte
=> Fix keyboard navigation
