- src/lib/components/button/button.svelte
- src/lib/components/input/asset.svelte
- src/lib/components/input/textinput.svelte
- src/routes/(dev)/debug/components/sections/inputs.svelte
- src/routes/(dev)/debug/input/asset/+page.svelte
Depends on `button-disabled-state` to prevent merge conflicts with formatting
Asset input and button onclick function have been fixed
> Fix asset input

- src/lib/components/button/button.svelte
- src/lib/components/input/asset.svelte
- src/lib/components/input/name.svelte
- src/lib/components/input/textinput.svelte
- src/lib/components/pageheader.svelte
- src/lib/components/progress.svelte
- src/routes/[network]/(account)/(send)/send/+page.svelte
- src/routes/[network]/(dev)/debug/components/sections/typography.svelte
Fixes input props and correctly passes HTMLInputAttributes (e.g. `id`) to the root component
Changes Asset component to use `type=number` for the number keyboard on mobile
Adds PageHeader component for consistent cross-page styling
Adds some additional styling and layout to the Send page
Fixes an issue with buttons in a flex context
Adds an animation on the Send page buttons
> Send input fixes

- src/lib/state/settings.svelte.ts
- src/routes/[network]/(account)/(send)/send/+page.svelte
- src/routes/[network]/settings/+page.svelte
Adds the `/settings` page, which contains:
- Language switcher
- Enable Advanced mode
- Enable Debug mode
Then altered the `/send` page to only display debugging information if the debug mode setting is true.
> Adding initial settings concept

- src/lib/components/button/button.svelte
- src/lib/components/input/search.svelte
- src/lib/components/input/textinput.svelte
- src/lib/components/navigation/mobilenavigation.svelte
- src/lib/components/navigation/sidemenu.svelte
- src/lib/components/select/account.svelte
- src/routes/[network]/(homepage)/+page.svelte
- src/routes/[network]/+layout.svelte
- moves the search input off the page into the layout
- creates a search dialog that can be clicked or triggered with a keyboard shortcut
- root layout has been changed to accommodate the new search component 
- root layout has been re-architected to use grids
- This lets us re-use components and move them around on mobile and desktop rather than hide them
- minor style fixes to colors and borders
> Search layout changes

- eslint.config.js
- src/lib/components/chart/rampricehistory.svelte
- src/lib/components/select/elements/index.ts
- src/lib/components/select/elements/item.svelte
- src/lib/components/select/elements/menu.svelte
- src/lib/components/select/elements/trigger.svelte
- src/lib/components/select/select.svelte
- src/lib/components/select/token.svelte
- src/lib/components/select/types.d.ts
- src/routes/[network]/(dev)/debug/components/sections/select.svelte
- src/routes/[network]/(dev)/debug/components/summaries/eosio/buyrambytes.svelte
Fixes type errors and refactors the token select to use an index vs the `tokenbalance` object
Note: generics across components is not well supported. Couldn't get it to work well, so the solution is twofold: 
1) either leave the type of the value key in the options array to be implicitly typed (e.g. `options: SelectOption[]` or `options: ExtendedSelectOption[]` instead of `options: SelectOption<number>[]`, see the examples in the debug page)
2) or, if you're passing in an array of objects that don't extend the `SelectOption` interface - create a custom writable store in the new select component which is typed to the object (e.g. the `TokenSelect` component takes `options: TokenBalance[]` and would implement `writable<TokenBalance>()` for the store. Note: in this case there is a step to …
> refactor: use index in token select value

- src/routes/+layout.svelte
the `extend` function was returning `object` and the expected type in `$derived` was `SeoConfig`
Also remove unused `onMount` import
> fix: type error in seoconfig

- src/app.d.ts
- src/error.html
- src/routes/+error.svelte
- src/routes/[network]/(explorer)/account/[name]/+layout.ts
- src/routes/[network]/+error.svelte
Adds a basic error page that re-uses the default layout so a user can still navigate if their search fails.
Still needs a design
Other 404s can still fail without getting the default layout since the UI is really being applied at `/src/routes/[network]/+layout.svelte`
Will need an alternative design for those errors. e.g. `/en/asdf` or `/en/eos/asdf`
> feat: basic error page

- Makefile
Now when installing packages if you use `make install package_name` it will run `bun install --yarn package_name` and keep the lockfile in sync
> chore: add install package command

- src/lib/components/input/switch.svelte
- src/routes/[network]/(dev)/debug/components/sections/inputs.svelte
- src/routes/[network]/settings/+page.svelte
Adds some styles to settings page.
Refactors switch component styling: 
- exclusively uses tailwind (no additional css transferred over the wire)
- enhances the usability on mobile and overall accessibility with increased sizing
> Settings page styles

- src/lib/assets/unicovelogo.svelte
- src/lib/components/footer.svelte
- src/lib/components/navigation/mobilenavigation.svelte
- src/lib/components/navigation/sidemenu.svelte
- src/routes/[network]/+layout.svelte
Link tag in the logo component was causing issues when it was inside a button (e.g. to trigger the mobile side menu)
> fix: bug with logo link

- src/lib/utils/index.ts
adding `stale-while-revalidate` could be very useful. Someone makes the request at 5.01 seconds and the cache is stale, so cloudflare can serve them that stale cache and revalidate it for the person that hits the same route at 5.02 seconds.
> feat: include stale-while-revalidate to cache-control

- src/lib/components/accountswitch.svelte
- src/lib/components/pageheader.svelte
Preload the chain logo in pageheader and account switcher. This will instruct the browser to prioritize this image which should reduce pop-in
> enhancement: preload chain logo

- src/lib/components/button/copy.svelte
- src/lib/components/pageheader.svelte
Adds a button to copy the account name from the page header
> feat: copy account name button

- src/lib/components/input/search.svelte
Result being saved to localstorage was duplicating language tag in URL after the fix with the `goto`, probably because the hooks only affect links.
> fix: search history links

- src/lib/components/accountswitch.svelte
- src/lib/components/pageheader.svelte
- src/routes/[network]/(homepage)/(wallets)/metamask/+page.svelte
- src/routes/[network]/(homepage)/+page.svelte
- src/routes/[network]/(homepage)/components/tlvhex.svelte
- src/routes/[network]/+layout.svelte
- Use the current network logo on homepage (e.g. Jungle 4, EOS)
- Refactor preloading to happen in layout instead of components
- Preload current chain logo, prefetch the others
- Use the `chainLogos` version of the EOS logo elsewhere to take advantage of the cached image
> Logo updates

- src/lib/components/descriptionlist.svelte
- src/lib/components/descriptionlist/dl.svelte
- src/lib/components/descriptionlist/dlrow.svelte
- src/lib/components/descriptionlist/index.ts
- src/lib/components/elements/account.svelte
- src/lib/utils/index.ts
- src/routes/[network]/(explorer)/block/[number]/+layout.svelte
- src/routes/[network]/(explorer)/block/[number]/+layout.ts
- src/routes/[network]/(explorer)/block/[number]/+page.svelte
- changed markup to use common components
- updated description list component to receive children
- combined and moved data processing to `layout.ts` 
I took some design liberties as follows:
- used a description list pattern instead of a table pattern for the block details. Reason: this is key-value data, not tabular data, and we have this pattern elsewhere so I'm changing it for consistency.
- right aligned numerical data
- Use `TransactionText` and `AccountText` components where applicable
> Dean block page

- src/lib/components/input/asset.svelte
- src/lib/components/input/bytes.svelte
- src/lib/components/input/number.svelte
- src/lib/components/input/text.svelte
Refactor the input component to better handle trailing elements.
Instead of absolute positioning the trailing element, the `TextInput` component now accepts a children snippet that will be slotted in place with the correct positioning. 
This also has the effect of ensuring the element is visible even if there is a long string of text in the input field
> Input trailing elements background

- src/lib/components/button/button.svelte
- src/lib/components/navigation/pillgroup.svelte
- src/routes/[network]/(account)/(send)/+layout.svelte
- src/routes/[network]/(dev)/debug/components/sections/navigation.svelte
- src/routes/[network]/(explorer)/account/[name]/+layout.svelte
- src/routes/[network]/(explorer)/block/[number]/+layout.svelte
- src/routes/[network]/(explorer)/contract/[contract]/+layout.svelte
- src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/+layout.svelte
Centralizing our active page check into the navigation component means we don't have to check in every layout.
Use `aria-current=page` instead of a custom `active` class for more semantic html and better a11y
> Refactor pill nav

- src/lib/components/button/button.svelte
Refactor button component styles for two reasons
1. Moves everything to tailwind classes removing the need for an additional stylesheet
2. Enables overriding default button classes in special cases
> refactor(button): allow overriding button classes

- src/lib/components/navigation/pillgroup.svelte
Implements dropdown selector for account page navigation on moblie
> feat: mobile page menu

- src/app.css
Fixes a style issue where the page would shift horizontally ~15px when navigating between a page with a scrollbar and a page without a scrollbar (e.g. from Home to My Account). This was most noticable in the left side navigation menu. 
With this change, the page maintains its horiztonal position regardless of a scrollbar.
> fix: horizontal shift on long pages

- src/lib/components/button/account.svelte
- src/lib/components/button/code.svelte
- src/lib/components/pageheader.svelte
- src/routes/[network]/(explorer)/+layout.svelte
> Add icon to page header if an account is a contract #348

- src/lib/utils/opengraph.ts
- src/routes/[network]/(account)/(send)/+layout.ts
- src/routes/[network]/(dev)/debug/+page.svelte
- src/routes/[network]/(dev)/debug/opengraph/+page.svelte
- src/routes/[network]/(dev)/debug/opengraph/+page.ts
- src/routes/[network]/+layout.server.ts
- src/routes/[network]/api/og/[...route].png/+server.ts
- src/routes/[network]/api/og/[...route].png/data.ts
This PR:
- add support for multiple layouts
- include token-based authentication for image generator service
- add test page for opengraph images at `/debug/opengraph`
- add basic index page for the various debug pages
The opengraph image needs to be accessible from a url like `http://unicove.com/en/eos/og_default.png` in the head of the document, but we also need some way of changing the image parameters e.g. title, text, layout, language, etc.
There were two approaches I considered to include all the various options we needed for generation:
1) add them to the image url like `http://unicove.com/en/eos/layout-1/Title%20of%20the%20image/Text%20of%20image/og_default.png` or `http://unicove.com/en/eos/og_default.png?text=Text%20of%20image&layout=1`
Upside to this approach is all …
> opengraph images

- src/lib/components/accountswitch.svelte
Closes #413 
Keeps the network switch component for future use
> refactor: remove network switch button from account switch sidebar

- src/lib/components/banner/pageBanner.svelte
Updated the href in the page banner component to reflect the new URL for the Vaulta page.
> Change page banner link to point to Vaulta resource

- src/lib/components/pageheader.svelte
- src/routes/[network]/(explorer)/+layout.svelte
- src/routes/[network]/(explorer)/account/[name]/+layout.ts
- src/routes/[network]/(explorer)/block/[number]/+layout.ts
- src/routes/[network]/(explorer)/contract/[contract]/+layout.ts
- src/routes/[network]/(explorer)/key/[publicKey]/+page.ts
- src/routes/[network]/(explorer)/msig/[proposer]/[proposal]/+layout.ts
- src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/+layout.ts
Pageheader actions (e.g. copy, switch between account/contract) are now defined in the page data (i.e. +page.ts) so each page can have custom actions or custom data to be copied
> refactor: pageheader actions

- src/lib/components/button/button.svelte
- src/routes/[network]/(homepage)/components/articles.svelte
- src/routes/[network]/(homepage)/components/staking-rewards.svelte
- src/routes/[network]/(homepage)/components/text-block.svelte
refactor the homepage link to be more generic and now any external link on the site (using the Button component) will have an icon indicating the user will be navigated away from unicove.com
> feat: add automatic icon for external button links

- src/app.css
- src/app.html
- src/lib/components/banner/pageBanner.svelte
- src/lib/components/button/button.svelte
- src/lib/components/elements/account.svelte
- src/lib/components/elements/block.svelte
- src/lib/components/elements/contract.svelte
- src/lib/components/elements/key.svelte
- src/lib/components/elements/tradingpair.svelte
- src/lib/components/elements/transaction.svelte
- src/lib/components/input/switch.svelte
- src/lib/components/navigation/sidemenu.svelte
- src/lib/components/select/elements/item.svelte
- src/routes/[network]/(account)/staking/+page.svelte
- src/routes/[network]/(dev)/debug/components/sections/colors.svelte
- src/routes/[network]/+layout.svelte
- src/routes/[network]/settings/+page.svelte
- tsconfig.json
Adds light mode that follows user OS preference
Adds toggle in settings to override OS preference
Adds color roles for `success` and `error`
Changes style of outlined buttons for lower contrast outline
Fixes contrast issues with sidemenu options
Fixes bug with label in settings
> style: add light theme

- src/lib/components/chip.svelte
- src/lib/components/elements/action.svelte
- src/lib/components/summary/components/balancechange.svelte
- src/routes/[network]/(explorer)/transaction/[id]/[[seq]]/+page.svelte
Refactor the transaction summary header layout to use grid for better alignment and more control on mobile screens
Minor fixes to related styles
> Transaction header styles
